name: Configurar Jupyter Book y GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install "jupyter-book==1.0.4.post1" ghp-import

      - name: Build book
        run: |
          jupyter-book clean . --all
          jupyter-book build .

      - name: Verificar carpeta generada
        run: |
          ls -la
          ls -la _build
          ls -la _build/html

      - name: Deploy to gh-pages
        run: |
          ghp-import -n -p -f _build/html